### PR TITLE
Expand the platform schema

### PR DESCRIPTION
**Pull request by mkellsy**
## Checklist:

-   [x] My code follows the code style of this project.
-   [ ] My change requires a change to the documentation.

## Types of changes

-   [x] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description of Changes

* Made the platform schema include all the fields, and made the oneOf an enum to feed the select fields.

## Reason for Change
* HOOBS config was missing the other fields

## How Has This Been Tested?

Tested on development HOOBS 3.1.11

## Screenshots (if appropriate):
Screen Shot 2019-12-26 at 12 04 07 PM

### CODE REVIEW

**Comment by tonesto7** [comment]
@mkellsy 
Won't this work with my config.schema.json thats for config-ui-x,  So I can maintain a single file?
Does certification require config platform.schema?

**Comment by mkellsy** [comment]
We support UI-X files too. But we can maintain the HOOBS specific file for you, ours loads a little quicker and supports things like buttons and actions.

**Comment by tonesto7** [comment]
@mkellsy Understood.  Thanks for the swift reply.   
I wasn't ever able to find any formal documentation on the formats beyond existing plugins as an example.  Did I miss something?

**Comment by mkellsy** [comment]
Plus, seeing that file is making me certify this faster :)

The schema files are a web standard. You can find the docs here
https://json-schema.org/

**Comment by THATDONFC** [comment]
Nice work! This is getting exciting.

**Pull request merged**
