### PR TITLE
Correct schema and prepare for HOOBS Certification

### PR DESCRIPTION
**Pull request by mkellsy**
## Checklist:

-   [x] My code follows the code style of this project.
-   [ ] My change requires a change to the documentation.

## Types of changes

-   [x] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description of Changes

* Fixed the platform.schema.json file
* Added the branding folder with a product.png
* Added the certified keywords to the package.json

## Reason for Change

The platform.schema.json file was mal-formatted, it was missing the "properties" object. I also removed the V2 from the alias, because, once certified it will be the only SmartThings plugin that will be certified.

I also added the certification categories to the package keywords.

## How Has This Been Tested?

I tested in the current development version of HOOBS 3.1.11. The changes are not used by vanilla Homebridge.

## Screenshots (if appropriate):
Screen Shot 2019-12-26 at 11 36 01 AM

Screen Shot 2019-12-26 at 11 35 49 AM

### CODE REVIEW

**Comment by tonesto7** [comment]
Thanks for doing this I will review today.  I have new release v2.1 rolling out in the week or so.  Will it need to be certified again?

**Comment by mkellsy** [comment]
Haven't certified it yet. I need to test it all first. I currently use V1 for my setup, so I can fully test the plugin.

After it is certified, we track updates and determine if the changes are breaking, required or minor. If they are required, we push the new version pretty quick. If it is minor, we fully test before publishing. If it is breaking, we will try to work with you to correct any issues.

So typically we tend to be a version behind, unless there are changes required by Samsung.

**Comment by tonesto7** [comment]
Ok so lets wait till v2.1 before performing certification.  I have a lot of bug squashed and services are cleaned up when no longer required.  
It's been in testing for awhile and in the dev branch if you want to begin testing.

**Comment by mkellsy** [comment]
No prob.

A little note. You can run `npm pack` on your project and it creates a **homebridge-smartthings-v2-[version].tgz** file that you can install and it works like if it were published.

```
sudo npm install -g --unsafe-perm /path-to-project/homebridge-smartthings-v2-[version].tgz
```

I always found that GitHub does things differently when you install from the repo.

**Comment by tonesto7** [comment]
thanks for the advice.  I didn't know this was an option :)

**Pull request merged**
